add wiki to socials 🥳
Hacking-in-Parallel-Berlin-22/HiP-22-Website pull request #2
Opened 2022-11-24 19:07 UTC by BlkPingu

added social icon w/ wiki link

2022-11-24 19:08 UTC, leifniem commented on src/components/Socials.astro
> +	<li class='matrix'>
I think we do not need the classes anymore, if you want to remove them.

2022-11-24 19:10 UTC, leifniem requested changes
Wiki icon fill needs to be #fff, also probably should be run through SVGOMG, just in case.

2022-11-24 19:21 UTC, BlkPingu commented
no time rn but putting it on the to-do list

2022-11-25 21:01 UTC, leifniem approved these changes

2022-11-25 21:01 UTC, merged